[package]
name = "shiinario_runtime"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
na_mpeg2_decoder = { path = "../na_mpeg2_decoder" }
anyhow.workspace = true
shiinario_assets.workspace = true
shiinario_scenario.workspace = true
serde.workspace = true
sha2.workspace = true
cpal = "0.15.3"
wgpu = "0.20"
winit = "0.30.13"
pollster = "0.3"
ab_glyph = "0.2.32"
encoding_rs.workspace = true

[dev-dependencies]
serde_json.workspace = true
flate2.workspace = true
